spring.datasource.url=jdbc:mysql://172.233.76.34:3306/jundb?socketTimeout=300000&autoReconnect=true&encrypt=false
spring.datasource.username=jenjun
spring.datasource.password=Jun@0123456789+-*/
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver